import type { Locale } from "../../i18n/translations";

const zh = {
  loading: "正在核对数字展厅资料……",
  loadErrorTitle: "数字展厅暂时无法打开",
  loadErrorText: "正式作品资料缺失、不兼容或未通过完整性核对。艺术家关系探索与序厅仍可正常参观。",
  backFoyer: "返回美术馆序厅",
  backConstellation: "返回艺术家关系探索",
  artistIndex: "艺术家索引",
  artistIndexEyebrow: "美术馆 · 数字展厅",
  artistIndexTitle: "每位艺术家，都是一个观看入口",
  artistIndexIntro: "按姓名、时期、地区或媒材查找艺术家。图像可用性只表示当前权利门禁结果，不表示艺术地位。",
  artistSearch: "搜索艺术家",
  artistSearchPlaceholder: "姓名、别名、地区或媒材",
  periodFilter: "时期",
  allPeriods: "全部时期",
  imageFilter: "作品图像",
  allImageStates: "全部状态",
  withImage: "有本站托管作品图",
  withoutImage: "当前无公开作品图",
  clearFilters: "清除筛选",
  artistResults: "显示 {count} 位艺术家",
  noArtistResults: "没有匹配的艺术家。调整搜索或筛选后再试。",
  openArtist: "进入艺术家展厅",
  works: "件正式作品",
  approvedWorks: "件作品有本站托管图像",
  relations: "条 C 级策展比较",
  noImage: "本记录没有通过公开媒体门禁的图像。",
  lowBandwidthImage: "低带宽模式不会自动请求图像；可单独选择加载这一件作品。",
  loadImage: "加载这件作品图像",
  imageLoading: "正在加载作品图像。",
  imageLoaded: "作品图像已加载。",
  imageUnavailable: "图像无法解码；作品元数据与官方来源仍然可用。",
  imageRights: "媒体署名与许可：",
  withdrawalStatus: "撤回状态：",
  officialSource: "访问官方作品来源",
  artistGalleryEyebrow: "艺术家数字展厅",
  reviewedIntro: "认识这位艺术家",
  timeline: "时间线摘要",
  lifeDates: "生卒",
  workRange: "本展作品年代",
  practice: "媒材与实践",
  context: "时期、地区与传统",
  formalWorks: "本展正式作品",
  relatedArtists: "相关艺术家",
  sourceRights: "介绍的依据",
  metadataRule: "元数据许可规则",
  metadataRuleBound: "已绑定公开来源条款",
  reviewRecord: "公开记录日期",
  viewArtwork: "查看作品详情",
  noRelatedArtists: "当前资料中还没有可显示的相关艺术家。",
  relatedUnavailable: "关系资料未能完成完整性核对；不会将失败伪装成空关系。",
  sourcesUnavailable: "完整来源资料暂不可用；请稍后从本页重试。",
  artworkEyebrow: "作品详情",
  artworkNotFound: "没有找到这件作品的正式记录。",
  artist: "艺术家",
  date: "年代",
  institution: "收藏机构",
  accession: "登录号",
  medium: "材料与技法",
  materials: "材料",
  techniques: "技法",
  subjects: "题材",
  originalTitle: "原文题名",
  originalTitleUnavailable: "当前正式数据未单独建模原文题名；不作推测。",
  evidence: "声明、证据与来源",
  claims: "支持声明",
  evidenceRecords: "证据记录",
  limitations: "证据边界",
  imageObservation: "图像观察",
  zoomHelp: "使用按钮、加减键或触控手势调整；平移只在放大后可用。",
  zoomIn: "放大",
  zoomOut: "缩小",
  zoomReset: "重置",
  zoomPercent: "缩放 {percent}%",
  zoomRegion: "可缩放作品图像",
  zoomUnavailable: "这件作品没有可用于放大观察的本站托管大图。",
  compareEyebrow: "双作比较",
  compareTitle: "把两件作品并置，慢一点看",
  compareIntro: "比较元数据、材料、技法、题材与年代；本页不计算视觉相似分数，也不自动推断影响。",
  chooseLeft: "选择左侧作品",
  chooseRight: "选择右侧作品",
  compareReady: "已选择两件不同作品",
  compareNeedsTwo: "请选择两件不同作品开始比较。",
  swapWorks: "交换两件作品",
  comparisonPrompts: "观察提示",
  prompts: [
    "两件作品如何处理相近或不同的材料？",
    "题材记录能支持哪些并置观察，又不能证明什么？",
    "年代与收藏机构的差异会怎样改变你的提问？",
  ],
  noSimilarity: "不提供 AI 视觉相似分数，不把并置写成历史影响。",
  compareLink: "比较这件作品",
  openCompare: "打开双作比较",
  imageDecision: "图像状态",
} as const;

const en = {
  loading: "Checking the digital-gallery release…",
  loadErrorTitle: "The digital galleries cannot open right now",
  loadErrorText: "The formal artwork release is missing, incompatible, or failed integrity checks. The constellation and foyer remain available.",
  backFoyer: "Back to the Art foyer",
  backConstellation: "Back to Artist Connections",
  artistIndex: "Artist index",
  artistIndexEyebrow: "Art Museum · Digital galleries",
  artistIndexTitle: "Each artist offers a way to begin looking",
  artistIndexIntro: "Find artists by name, period, region, or medium. Image availability reflects only the current rights gate, never artistic status.",
  artistSearch: "Search artists",
  artistSearchPlaceholder: "Name, alias, region, or medium",
  periodFilter: "Period",
  allPeriods: "All periods",
  imageFilter: "Artwork images",
  allImageStates: "All image states",
  withImage: "Site-hosted artwork image available",
  withoutImage: "No public artwork image now",
  clearFilters: "Clear filters",
  artistResults: "Showing {count} artists",
  noArtistResults: "No artists match. Adjust the search or filters and try again.",
  openArtist: "Enter artist gallery",
  works: "formal works",
  approvedWorks: "works with site-hosted images",
  relations: "C-level curatorial comparisons",
  noImage: "No image passed the public-media gate for this record.",
  lowBandwidthImage: "Low-bandwidth mode makes no automatic image request; you may load this work individually.",
  loadImage: "Load this artwork image",
  imageLoading: "Loading the artwork image.",
  imageLoaded: "Artwork image loaded.",
  imageUnavailable: "The image could not be decoded; artwork metadata and the official source remain available.",
  imageRights: "Media attribution and license:",
  withdrawalStatus: "Withdrawal status:",
  officialSource: "Visit official artwork source",
  artistGalleryEyebrow: "Artist digital gallery",
  reviewedIntro: "Meet the artist",
  timeline: "Timeline summary",
  lifeDates: "Life dates",
  workRange: "Works in this release",
  practice: "Media and practice",
  context: "Period, region, and tradition",
  formalWorks: "Formal works in this release",
  relatedArtists: "Related artists",
  sourceRights: "What supports the introduction",
  metadataRule: "Metadata license rule",
  metadataRuleBound: "Bound to published source terms",
  reviewRecord: "Public record date",
  viewArtwork: "View artwork detail",
  noRelatedArtists: "The current material has no related artists to show yet.",
  relatedUnavailable: "Relationship data failed its integrity check; the failure is not presented as an empty result.",
  sourcesUnavailable: "Complete source material is temporarily unavailable; retry from this page later.",
  artworkEyebrow: "Artwork detail",
  artworkNotFound: "No formal record was found for this artwork.",
  artist: "Artist",
  date: "Date",
  institution: "Institution",
  accession: "Accession number",
  medium: "Materials and techniques",
  materials: "Materials",
  techniques: "Techniques",
  subjects: "Subjects",
  originalTitle: "Original-language title",
  originalTitleUnavailable: "The formal release does not model a separate original-language title; none is inferred.",
  evidence: "Claims, evidence, and sources",
  claims: "Supporting Claims",
  evidenceRecords: "Evidence records",
  limitations: "Evidence boundary",
  imageObservation: "Image observation",
  zoomHelp: "Use the buttons, plus/minus keys, or touch gestures; panning is available only after zooming.",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  zoomReset: "Reset",
  zoomPercent: "Zoom {percent}%",
  zoomRegion: "Zoomable artwork image",
  zoomUnavailable: "No site-hosted large image is available for zooming this work.",
  compareEyebrow: "Two-work comparison",
  compareTitle: "Place two works together, then look slowly",
  compareIntro: "Compare metadata, materials, techniques, subjects, and dates. This page calculates no visual-similarity score and infers no influence.",
  chooseLeft: "Choose the left work",
  chooseRight: "Choose the right work",
  compareReady: "Two different works selected",
  compareNeedsTwo: "Choose two different works to begin comparing.",
  swapWorks: "Swap works",
  comparisonPrompts: "Observation prompts",
  prompts: [
    "How do the two works handle similar or different materials?",
    "What can the recorded subjects support as an observation, and what can they not prove?",
    "How might different dates and institutions change the questions you ask?",
  ],
  noSimilarity: "No AI visual-similarity score is produced, and juxtaposition is never rewritten as historical influence.",
  compareLink: "Compare this work",
  openCompare: "Open two-work comparison",
  imageDecision: "Image status",
} as const;

export const galleryCopy = { "zh-CN": zh, en } as const satisfies Record<Locale, object>;

export function fillCopy(template: string, values: Record<string, string | number>) {
  return Object.entries(values).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
    template,
  );
}
